version: '3.4'

services:
  koa-drive:
    image: koa-drive
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 7200
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js